### ISSUE TITLE
Support Node version management tools

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/release-toolkit-gutenberg-mobile#157]
When using the [SetupNode](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/76a6b40b2494ed12f2752a5931b38a80c2efc370/cli/pkg/exec/exec.go#L22-L30) function, we should support alternate Node version management tools beyond `nvm` (such as [`asdf`](https://asdf-vm.com/)).

**Comment by jhnstn** [comment]
Right now `nvm` is not a hard requirement but since nvm is recommended in the [block editor dev docs](https://developer.wordpress.org/block-editor/getting-started/devenv/) the gbm cli tool looks to see if it can use it.

It's not a hard requirement but if the global node version is incorrect then the build steps will likely fail.
